# -*- coding: utf-8 -*-
# 
# F5 Dashboard for OpenStack Neutron LBaaS documentation build configuration file.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath('.'))

import f5_sphinx_theme

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.4'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.viewcode',
    'sphinx.ext.extlinks',
    'cloud_sptheme.ext.table_styling',
    'sphinxjp.themes.basicstrap',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'F5 Dashboard for OpenStack Neutron LBaaS'
copyright = u'2018 F5 Networks'
author = u'F5 Networks'

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'f5_sphinx_theme'
html_theme_path = f5_sphinx_theme.get_html_theme_path()

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
                        #'site_name': 'F5 OpenStack Docs Home',
                        'next_prev_link': False
                     }

# The name for this set of Sphinx documents.
# "<project> v<release> documentation" by default.
html_title = u'F5 Dashboard for OpenStack Neutron LBaaS'
short_title = u'F5 Dashboard'


version = '9.0.0'

rst_epilog = '''
.. |dashboard| replace:: f5-neutron-lbaas-dashboard
.. |dashboard-short| replace:: F5 Dashboard
.. |dashboard-long| replace:: F5 Dashboard for OpenStack Neutron LBaaS
.. |f5_dashboard_rpm_package| replace:: f5-neutron-lbaas-dashboard-%(version)s-1.el7.noarch.rpm
.. |f5_dashboard_rpm_url| replace:: https://github.com/F5Networks/neutron-lbaas-dashboard/releases/download/v%(version)s/f5-neutron-lbaas-dashboard-%(version)s-1.el7.noarch.rpm
.. |rpm-download| raw:: html

    <a class="btn btn-info" href="https://github.com/F5Networks/neutron-lbaas-dashboard/releases/download/v%(version)s/f5-neutron-lbaas-dashboard-%(version)s-1.el7.noarch.rpm">RPM package</a>
''' % {
  'version': version,
}

linkcheck_ignore = [r'https://review.openstack.org/#.+']
